"""user updated

Revision ID: 6fccdc01bded
Revises: a66a4a4b908e
Create Date: 2023-10-25 18:16:07.013015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fccdc01bded'
down_revision = 'a66a4a4b908e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
